spring:
  application:
    name: Problem-Contest-Service

  data:
    cassandra:
      port: 9042
      keyspace-name: problems_and_contest
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-deadcoder11u2.herokuapp.com/eureka/
